### PR TITLE
changed version to 1.2.1 and updated release notes

### PR DESCRIPTION
**Pull request by davidcui1225**
*Issue #, if available:*
#26 
*Description of changes:*
Updated version and release notes. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dai-chen** [comment]
One more place needs update: https://github.com/opendistro-for-elasticsearch/sql-jdbc/pull/18/files#diff-5122c694f3a3e08d9283832fbc8ef017L22

**Review by dai-chen — COMMENTED** [review]
Please change the `Version` class accordingly as I commented.

**Comment by davidcui1225** [comment]
> One more place needs update: https://github.com/opendistro-for-elasticsearch/sql-jdbc/pull/18/files#diff-5122c694f3a3e08d9283832fbc8ef017L22

good catch, thanks! Will update and test

**Review by dai-chen — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
